// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Access Vite env variables using import.meta.env
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase env vars missing. Check VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.");
}

// Ensure every request carries the anon key (safety net for 406/400 missing apikey)
const withApiKeyFetch: typeof fetch = (input, init) => {
  const headers = new Headers(init?.headers ?? {});
  // Always set apikey
  headers.set("apikey", SUPABASE_PUBLISHABLE_KEY);
  // If no Authorization was provided, fall back to anon key so PostgREST sees a valid token
  if (!headers.has("Authorization")) {
    headers.set("Authorization", `Bearer ${SUPABASE_PUBLISHABLE_KEY}`);
  }
  return fetch(input, { ...init, headers });
};

// Create Supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        apikey: SUPABASE_PUBLISHABLE_KEY,
      },
    },
    fetch: withApiKeyFetch,
  }
);

// Expose client in dev for debugging in browser console
if (import.meta.env.DEV) {
  (window as any).supabase = supabase;
}
